### ISSUE TITLE
Can't get Sierpinski shaders working

### ISSUE THREAD

**Issue by bendavidsteel** [pedrotrschneider/shader-fractals#2]
Hi! Thanks for putting these on Github, really enjoying playing around with them. The Mandelbulb and Mandelbox shaders work great, but I've having trouble getting the 3D Sierpinski based shaders to work even when I put them line for line into shadertoy.

When I put them into shadertoy I get just a solid colour screen, which I think means there is some the rays are never hitting the fractal somehow? I'm trying to figure out why that is but I'm still fairly new to GLSL.

Is it possible the shaders for those of out of date? Would love to try them out

**Comment by pedrotrschneider** [comment]
Hi! Thanks for reaching out! 
Man, it's been a while since I've worked on this project lol. But it's weird, iirc the code for all 3d fractals is basicaly the same, so it's odd that some of them work and some don't. Give me a couple of hours and I think I'll have the time to try them out on sahdertoy.
Since it's been so long, it's possible that they are out of date due to some change on shadertoy.
I'll check it out and get back to you in a couple of days max.

**Comment by bendavidsteel** [comment]
Thanks for getting back to me! Really appreciate any help, but obvs don't feel rushed, i'll eventually work out the problem and will update here:)

**Comment by bendavidsteel** [comment]
Worked out the issue! Created a pull request here #3

**Comment by pedrotrschneider** [comment]
I'm so sorry for not getting back to you in so long!
Thanks a lot for the PR! I'll be reviewing it shortly and, if everything works, I'll merge it.
Thanks again, and sorry for the time it took.

**Comment by pedrotrschneider** [comment]
Reviewed the PR and it all works like a charm. Not really sure why it broke in the first place, but it works!
I'll be closing this issue now.
Thanks again :)
